// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server;

namespace server.Migrations
{
    [DbContext(typeof(StatTrackerContext))]
    [Migration("20181022195734_AddedPlayerStatsTable2")]
    partial class AddedPlayerStatsTable2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("server.PlayerStats", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PassingAttempts");

                    b.Property<int>("PassingCompletions");

                    b.Property<int>("PassingTouchdowns");

                    b.Property<int>("PassingYards");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("PlayerStat");
                });
#pragma warning restore 612, 618
        }
    }
}
